name: Flutter Application Check and Publish CI

on: push

jobs:
  flutter-check-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Flutter dependencies
        run: |
          flutter config --no-analytics --no-cli-animations
          flutter --version
          flutter pub get

      - name: Check code formatting
        run: |
          dart format --output=none --set-exit-if-changed .

      - name: Check for code errors
        run: flutter analyze

      - name: Build prod
        run: flutter build web --release

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == "refs/heads/main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
